update bootstrap to warn about rm .bashrc

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -10,17 +10,38 @@ require_cmd() {
   }
 }
 
+confirm_remove() {
+  local target="$1"
+
+  if [ -e "$target" ] || [ -L "$target" ]; then
+    echo "warning: $target already exists"
+    read -r -p "remove it and continue? [y/N] " reply
+    case "$reply" in
+      y|Y|yes|YES)
+        rm -rf "$target"
+        echo "removed $target"
+        ;;
+      *)
+        echo "aborted"
+        exit 1
+        ;;
+    esac
+  fi
+}
+
 echo "==> checking prerequisites"
 require_cmd git
 
 echo "==> installing system dependencies"
 "$ROOT_DIR/script/install-deps-ubuntu"
 
-echo "==> installing neovim"
-"$ROOT_DIR/script/install-neovim"
-
 echo "==> checking required tools after dependency install"
 require_cmd stow
+
+confirm_remove "$HOME/.bashrc"
+
+echo "==> installing neovim"
+"$ROOT_DIR/script/install-neovim"
 
 echo "==> stowing dotfiles"
 "$ROOT_DIR/script/stow-dotfiles"
